% orden/1 captura los ordenes de la clase de los mamiferos.%
orden(afrosoricida).
orden(artiodactyla).
orden(carnivora).
orden(cetacea).
orden(chiroptera).
orden(cingulata).
orden(dasyuromorphia).
orden(dermoptera).
orden(didelphimorphia).
orden(diprotodontia).
orden(erinaceomorpha).
orden(hyracoidea).
orden(lagomorpha).
orden(macroscelidea).
orden(microbiotheria).
orden(monotremata).
orden(notoryctemorphia).
orden(paucituberculata).
orden(peramelemorphia).
orden(perissodactyla).
orden(pholidota).
orden(pilosa).
orden(primates).
orden(proboscidea).
orden(rodentia).
orden(scandentia).
orden(sirenia).
orden(soricomorpha).
orden(tubulidentata).

orden(cetartiodactyla).
orden(eulipotyphla).



% familia/2 captura las familias de la clase de los mamiferos.
familia(abrocomidae).
familia(acaremyidae).
familia(acrobatidae).
familia(ailuridae).
familia(amebelodontidae).
familia(amphilestidae).
familia(anancidae).
familia(anomaluridae).
familia(antilocapridae).
familia(aplodontiidae).
familia(argyrolagidae).
familia(arsinoitheriidae).
familia(balaenidae).
familia(balaenopteridae).
familia(barytheriidae).
familia(bathyergidae).
familia(borhyaenidae).
familia(bovidae).
familia(bradypodidae).
familia(burramyidae).
familia(caenolestidae).
familia(cainotheriidae).
familia(callitrichidae).
familia(calomyscidae).
familia(camelidae).
familia(canidae).
familia(castoridae).
familia(caviidae).
familia(cebidae).
familia(cercopithecidae).
familia(cervidae).
familia(chaeropodidae).
familia(cheirogaleidae).
familia(chinchillidae).
familia(chlamyphoridae).
familia(chrysochloridae).
familia(craseonycteridae).
familia(cricetidae).
familia(ctenodactylidae).
familia(ctenomyidae).
familia(cuniculidae).
familia(cyclopedidae).
familia(cynocephalidae).
familia(dasypodidae).
familia(dasyproctidae).
familia(dasyuridae).
familia(daubentoniidae).
familia(deinotheriidae).
familia(delphinidae).
familia(diatomyidae).
familia(didelphidae).
familia(didymoconidae).
familia(dinomyidae).
familia(dipodidae).
familia(dugongidae).
familia(echimyidae).
familia(elephantidae).
familia(emballonuridae).
familia(eomyidae).
familia(equidae).
familia(erethizontidae).
familia(erinaceidae).
familia(felidae).
familia(furipteridae).
familia(galagidae).
familia(geomyidae).
familia(giraffidae).
familia(gliridae).
familia(gomphotheriidae).
familia(groeberiidae).
familia(herpestidae).
familia(heteromyidae).
familia(hippopotamidae).
familia(hipposideridae).
familia(hominidae).
familia(hoplitomerycidae).
familia(hyaenidae).
familia(hylobatidae).
familia(hypsiprymnodontidae).
familia(hystricidae).
familia(indriidae).
familia(iniidae).
familia(lemuridae).
familia(lepilemuridae).
familia(leporidae).
familia(lipotidae).
familia(lorisidae).
familia(macropodidae).
familia(macroscelididae).
familia(manidae).
familia(megadermatidae).
familia(megalonychidae).
familia(mephitidae).
familia(microbiotheriidae).
familia(microsyopidae).
familia(molossidae).
familia(monodontidae).
familia(mormoopidae).
familia(moschidae).
familia(muridae).
familia(mustelidae).
familia(mylagaulidae).
familia(myrmecobiidae).
familia(myrmecophagidae).
familia(mystacinidae).
familia(myzopodidae).
familia(nandiniidae).
familia(neoepiblemidae).
familia(nesomyidae).
familia(noctilionidae).
familia(notoryctidae).
familia(numidotheriidae).
familia(nycteridae).
familia(ochotonidae).
familia(octodontidae).
familia(odobenidae).
familia(ornithorhynchidae).
familia(orycteropodidae).
familia(otariidae).
familia(pampatheriidae).
familia(pedetidae).
familia(peramelidae).
familia(petauridae).
familia(petromuridae).
familia(phalangeridae).
familia(phascolarctidae).
familia(phocidae).
familia(phocoenidae).
familia(phyllostomidae).
familia(physeteridae).
familia(platacanthomyidae).
familia(platanistidae).
familia(pontoporiidae).
familia(potoroidae).
familia(prionodontidae).
familia(proborhyaenidae).
familia(procaviidae).
familia(procyonidae).
familia(prorastomidae).
familia(protosirenidae).
familia(pseudocheiridae).
familia(pseudorhyncocyonidae).
familia(pteropodidae).
familia(ptilocercidae).
familia(rhinocerotidae).
familia(rhinolophidae).
familia(rhinopomatidae).
familia(sciuridae).
familia(solenodontidae).
familia(soricidae).
familia(spalacidae).
familia(sparassocynidae).
familia(suidae).
familia(tachyglossidae).
familia(talpidae).
familia(tapiridae).
familia(tarsiidae).
familia(tarsipedidae).
familia(tayassuidae).
familia(tenrecidae).
familia(thryonomyidae).
familia(thylacomyidae).
familia(thylacosmilidae).
familia(thyropteridae).
familia(tragulidae).
familia(trichechidae).
familia(tupaiidae).
familia(ursidae).
familia(vespertilionidae).
familia(viverridae).
familia(vombatidae).
familia(ziphiidae).



% pertenece/2 captura en el primer parametro la familia y en el
% segundo parametro el orden al que pertenece la familia.%
pertenece(abrocomidae,rodentia).
pertenece(acaremyidae,rodentia).
pertenece(acrobatidae,diprotodontia).
pertenece(ailuridae,carnivora).
pertenece(amebelodontidae,proboscidea).
pertenece(amphilestidae,eutriconodonta).
pertenece(anancidae,proboscidea).
pertenece(anomaluridae,rodentia).
pertenece(antilocapridae,artiodactyla).
pertenece(aplodontiidae,rodentia).
pertenece(argyrolagidae,paucituberculata).
pertenece(arsinoitheriidae,embrithopoda).
pertenece(balaenidae,cetacea).
pertenece(balaenopteridae,cetacea).
pertenece(barytheriidae,proboscidea).
pertenece(bathyergidae,rodentia).
pertenece(borhyaenidae,sparassodonta).
pertenece(bovidae,artiodactyla).
pertenece(bradypodidae,pilosa).
pertenece(burramyidae,diprotodontia).
pertenece(caenolestidae,paucituberculata).
pertenece(cainotheriidae,artiodactyla).
pertenece(callitrichidae,primates).
pertenece(calomyscidae,rodentia).
pertenece(camelidae,artiodactyla).
pertenece(canidae,carnivora).
pertenece(castoridae,rodentia).
pertenece(caviidae,rodentia).
pertenece(cebidae,primates).
pertenece(cercopithecidae,primates).
pertenece(cervidae,artiodactyla).
pertenece(chaeropodidae,peramelemorphia).
pertenece(cheirogaleidae,primates).
pertenece(chinchillidae,rodentia).
pertenece(chlamyphoridae,cingulata).
pertenece(chrysochloridae,afrosoricida).
pertenece(craseonycteridae,chiroptera).
pertenece(cricetidae,rodentia).
pertenece(ctenodactylidae,rodentia).
pertenece(ctenomyidae,rodentia).
pertenece(cuniculidae,rodentia).
pertenece(cyclopedidae,pilosa).
pertenece(cynocephalidae,dermoptera).
pertenece(dasypodidae,cingulata).
pertenece(dasyproctidae,rodentia).
pertenece(dasyuridae,dasyuromorphia).
pertenece(daubentoniidae,primates).
pertenece(deinotheriidae,proboscidea).
pertenece(delphinidae,cetacea).
pertenece(diatomyidae,rodentia).
pertenece(didelphidae,didelphimorphia).
pertenece(didymoconidae,leptictida).
pertenece(dinomyidae,rodentia).
pertenece(dipodidae,rodentia).
pertenece(dugongidae,sirenia).
pertenece(echimyidae,rodentia).
pertenece(elephantidae,proboscidea).
pertenece(emballonuridae,chiroptera).
pertenece(enaliarctidae,carnivora).
pertenece(eomyidae,rodentia).
pertenece(equidae,perissodactyla).
pertenece(erethizontidae,rodentia).
pertenece(erinaceidae,erinaceomorpha).
pertenece(felidae,carnivora).
pertenece(furipteridae,chiroptera).
pertenece(galagidae,primates).
pertenece(geomyidae,rodentia).
pertenece(giraffidae,artiodactyla).
pertenece(gliridae,rodentia).
pertenece(gomphotheriidae,proboscidea).
pertenece(groeberiidae,gondwanatheria).
pertenece(herpestidae,carnivora).
pertenece(heteromyidae,rodentia).
pertenece(hipposideridae,chiroptera).
pertenece(hippopotamidae,artiodactyla).
pertenece(hominidae,primates).
pertenece(hoplitomerycidae,artiodactyla).
pertenece(hyaenidae,carnivora).
pertenece(hylobatidae,primates).
pertenece(hypsiprymnodontidae,diprotodontia).
pertenece(hystricidae,rodentia).
pertenece(indriidae,primates).
pertenece(iniidae,cetacea).
pertenece(kollikodontidae,monotremata).
pertenece(lemuridae,primates).
pertenece(lepilemuridae,primates).
pertenece(leporidae,lagomorpha).
pertenece(lipotidae,cetacea).
pertenece(lorisidae,primates).
pertenece(macropodidae,diprotodontia).
pertenece(macroscelididae,macroscelidea).
pertenece(mammutidae,proboscidea).
pertenece(manidae,pholidota).
pertenece(megadermatidae,chiroptera).
pertenece(megalonychidae,pilosa).
pertenece(mephitidae,carnivora).
pertenece(microbiotheriidae,microbiotheria).
pertenece(microsyopidae,plesiadapiformes).
pertenece(molossidae,chiroptera).
pertenece(monodontidae,cetacea).
pertenece(mormoopidae,chiroptera).
pertenece(moschidae,artiodactyla).
pertenece(muridae,rodentia).
pertenece(mustelidae,carnivora).
pertenece(mylagaulidae,rodentia).
pertenece(myrmecobiidae,dasyuromorphia).
pertenece(myrmecophagidae,pilosa).
pertenece(mystacinidae,chiroptera).
pertenece(myzopodidae,chiroptera).
pertenece(nandiniidae,carnivora).
pertenece(neoepiblemidae,rodentia).
pertenece(nesomyidae,rodentia).
pertenece(nimravidae,carnivora).
pertenece(noctilionidae,chiroptera).
pertenece(notoryctidae,notoryctemorphia).
pertenece(numidotheriidae,proboscidea).
pertenece(nycteridae,chiroptera).
pertenece(ochotonidae,lagomorpha).
pertenece(octodontidae,rodentia).
pertenece(odobenidae,carnivora).
pertenece(ornithorhynchidae,monotremata).
pertenece(orycteropodidae,tubulidentata).
pertenece(otariidae,carnivora).
pertenece(pampatheriidae,cingulata).
pertenece(pedetidae,rodentia).
pertenece(peramelidae,peramelemorphia).
pertenece(petauridae,diprotodontia).
pertenece(petromuridae,rodentia).
pertenece(phalangeridae,diprotodontia).
pertenece(phascolarctidae,diprotodontia).
pertenece(phocidae,carnivora).
pertenece(phocoenidae,cetacea).
pertenece(phyllostomidae,chiroptera).
pertenece(physeteridae,cetacea).
pertenece(platacanthomyidae,rodentia).
pertenece(platanistidae,cetacea).
pertenece(pontoporiidae,cetacea).
pertenece(potoroidae,diprotodontia).
pertenece(prionodontidae,carnivora).
pertenece(proborhyaenidae,sparassodonta).
pertenece(procaviidae,hyracoidea).
pertenece(procyonidae,carnivora).
pertenece(prorastomidae,sirenia).
pertenece(protosirenidae,sirenia).
pertenece(pseudocheiridae,diprotodontia).
pertenece(pseudorhyncocyonidae,leptictida).
pertenece(pteropodidae,chiroptera).
pertenece(ptilocercidae,scandentia).
pertenece(rhinocerotidae,perissodactyla).
pertenece(rhinolophidae,chiroptera).
pertenece(rhinopomatidae,chiroptera).
pertenece(sciuridae,rodentia).
pertenece(solenodontidae,soricomorpha).
pertenece(soricidae,soricomorpha).
pertenece(spalacidae,rodentia).
pertenece(sparassocynidae,didelphimorphia).
pertenece(stegodontidae,proboscidea).
pertenece(steropodontidae,monotremata).
pertenece(suidae,artiodactyla).
pertenece(tachyglossidae,monotremata).
pertenece(talpidae,soricomorpha).
pertenece(tapiridae,perissodactyla).
pertenece(tarsiidae,primates).
pertenece(tarsipedidae,diprotodontia).
pertenece(tayassuidae,artiodactyla).
pertenece(tenrecidae,afrosoricida).
pertenece(thryonomyidae,rodentia).
pertenece(thylacomyidae,peramelemorphia).
pertenece(thylacosmilidae,sparassodonta).
pertenece(thyropteridae,chiroptera).
pertenece(tragulidae,artiodactyla).
pertenece(trichechidae,sirenia).
pertenece(tupaiidae,scandentia).
pertenece(ursidae,carnivora).
pertenece(vespertilionidae,chiroptera).
pertenece(viverridae,carnivora).
pertenece(vombatidae,diprotodontia).
pertenece(ziphiidae,cetacea).

pertenece(Familia,artiodactyla):- pertenece(Familia,cetacea).
pertenece(Familia,cetartiodactyla):- pertenece(Familia,artiodactyla).
pertenece(Familia,eulipotyphla):- pertenece(Familia,erinaceomorpha).
pertenece(Familia,eulipotyphla):- pertenece(Familia,soricomorpha).



extinto(Orden):- pertenece(_,Orden), not(orden(Orden)), write("Orden: "), write(Orden), nl, fail. %Pueden ser ordenes extintas.
extinto(Familia):- pertenece(Familia,_), not(familia(Familia)), write("Familia: "), write(Familia), nl, fail. %Pueden ser familias extintas.



animal(hipopotamo):- familia(hippopotamidae), pertenece(hippopotamidae,Orden),
    write("Su Familia es "+hippopotamidae), nl, write("Su Orden es "+Orden).
animal(tigre):- X = felidae, familia(X), pertenece(X,Orden),
    write("Su Familia es "+X), nl, write("Su Orden es "+Orden).
animal(murcielago):- X = chiroptera, orden(X), pertenece(Familia,X),
    write("Su Familia es "+Familia), nl, write("Su Orden es "+X).



caracteristica(afrosoricida,theria).
caracteristica(afrosoricida,eutheria).
caracteristica(afrosoricida,endemico_africa).
caracteristica(afrosoricida,insectivoro).
caracteristica(afrosoricida,pequeno).
caracteristica(afrosoricida,hocico_alargado).
caracteristica(afrosoricida,plantigrado).
caracteristica(afrosoricida,terrestre).
caracteristica(afrosoricida,fosorial).
caracteristica(afrosoricida,macrosmatico).
caracteristica(afrosoricida,omnivoro).
caracteristica(afrosoricida,puas_o_espinas).
caracteristica(afrosoricida,pelaje).
caracteristica(afrosoricida,ojos_diminutos).
caracteristica(afrosoricida,pentadactilo).
caracteristica(afrosoricida,garras).
caracteristica(afrosoricida,venenoso).
caracteristica(afrosoricida,nocturno).

caracteristica(artiodactyla,theria).
caracteristica(artiodactyla,eutheria).
caracteristica(artiodactyla,ungulado).
caracteristica(artiodactyla,herbivoro).
caracteristica(artiodactyla,escroto).
caracteristica(artiodactyla,pelaje).
caracteristica(artiodactyla,robusto).
caracteristica(artiodactyla,digitigrado).
caracteristica(artiodactyla,dedos_pares).
caracteristica(artiodactyla,pezunas).
caracteristica(artiodactyla,terrestre).
caracteristica(artiodactyla,mediano).
caracteristica(artiodactyla,grande).
caracteristica(artiodactyla,muy_grande).

caracteristica(carnivora,theria).
caracteristica(carnivora,eutheria).
caracteristica(carnivora,escroto).
caracteristica(carnivora,dedos_min_cuatro).
caracteristica(carnivora,carnivoro).
caracteristica(carnivora,garras).
caracteristica(carnivora,caninos_desarrollados).
caracteristica(carnivora,carniceras_desarrollados).
caracteristica(carnivora,sin_diastema).
caracteristica(carnivora,terrestre).
caracteristica(carnivora,pelaje).
caracteristica(carnivora,dedos_pares).
caracteristica(carnivora,dedos_impares).
caracteristica(carnivora,dedos_traseros_cuatro).
caracteristica(carnivora,dedos_delanteros_cinco).
caracteristica(carnivora,omnivoro).
caracteristica(carnivora,semiacuatico).
caracteristica(carnivora,aletas).
caracteristica(carnivora,digitigrado).
caracteristica(carnivora,plantigrado).
caracteristica(carnivora,pequeno).
caracteristica(carnivora,mediano).
caracteristica(carnivora,grande).
caracteristica(carnivora,muy_grande).

caracteristica(cetacea,theria).
caracteristica(cetacea,eutheria).
caracteristica(cetacea,ungulado).
caracteristica(cetacea,acuatico).
caracteristica(cetacea,dedos_pares).
caracteristica(cetacea,carnivoro).
caracteristica(cetacea,aletas).
caracteristica(cetacea,robusto).
caracteristica(cetacea,piel_gruesa).
caracteristica(cetacea,sin_dientes).
caracteristica(cetacea,espiraculo).
caracteristica(cetacea,grande).
caracteristica(cetacea,muy_grande).
caracteristica(cetacea,ecolocacion).

caracteristica(chiroptera,theria).
caracteristica(chiroptera,eutheria).
caracteristica(chiroptera,escroto).
caracteristica(chiroptera,dedos_min_cuatro).
caracteristica(chiroptera,aereo).
caracteristica(chiroptera,patagio).
caracteristica(chiroptera,incisivos_no_desarrollados).
caracteristica(chiroptera,insectivoro).
caracteristica(chiroptera,frugivoro).
caracteristica(chiroptera,hematofago).
caracteristica(chiroptera,garras).
caracteristica(chiroptera,ecolocacion).
caracteristica(chiroptera,nocturno).
caracteristica(chiroptera,pelaje).
caracteristica(chiroptera,pentadactilo).
caracteristica(chiroptera,venenoso).
caracteristica(chiroptera,macrosmatico).
caracteristica(chiroptera,plantigrado).

caracteristica(cingulata,theria).
caracteristica(cingulata,eutheria).
caracteristica(cingulata,articulaciones_xenartrales).
caracteristica(cingulata,sin_dientes).
caracteristica(cingulata,dientes_no_desarrollados).
caracteristica(cingulata,sin_caninos).
caracteristica(cingulata,sin_incisivos).
caracteristica(cingulata,placa_osea).
caracteristica(cingulata,insectivoro).
caracteristica(cingulata,endemico_america).
caracteristica(cingulata,terrestre).
caracteristica(cingulata,garras).
caracteristica(cingulata,piel_gruesa).
caracteristica(cingulata,lengua_protactil).
caracteristica(cingulata,dedos_min_cuatro).
caracteristica(cingulata,hocico_alargado).
caracteristica(cingulata,pequeno).
caracteristica(cingulata,mediano).
caracteristica(cingulata,macrosmatico).
caracteristica(cingulata,fosorial).
caracteristica(cingulata,plantigrado).

caracteristica(dasyuromorphia,theria).
caracteristica(dasyuromorphia,metatheria).
caracteristica(dasyuromorphia,endemico_australia).
caracteristica(dasyuromorphia,carnivoro).
caracteristica(dasyuromorphia,poliprotodonto).
caracteristica(dasyuromorphia,carniceras_desarrollados).
caracteristica(dasyuromorphia,insectivoro).
caracteristica(dasyuromorphia,terrestre).
caracteristica(dasyuromorphia,garras).
caracteristica(dasyuromorphia,pelaje).
caracteristica(dasyuromorphia,dedos_min_cuatro).
caracteristica(dasyuromorphia,pequeno).
caracteristica(dasyuromorphia,mediano).
caracteristica(dasyuromorphia,nocturno).
caracteristica(dasyuromorphia,plantigrado).
caracteristica(dasyuromorphia,sindactilos).
caracteristica(dasyuromorphia,digitigrado).

caracteristica(dermoptera,theria).
caracteristica(dermoptera,eutheria).
caracteristica(dermoptera,escroto).
caracteristica(dermoptera,dedos_min_cuatro).
caracteristica(dermoptera,pentadactilo).
caracteristica(dermoptera,arboricola).
caracteristica(dermoptera,patagio).
caracteristica(dermoptera,dedos_palmeados).
caracteristica(dermoptera,frugivoro).
caracteristica(dermoptera,herbivoro).
caracteristica(dermoptera,plantigrado).
caracteristica(dermoptera,terrestre).
caracteristica(dermoptera,pelaje).
caracteristica(dermoptera,garras).
caracteristica(dermoptera,pequeno).
caracteristica(dermoptera,mediano).
caracteristica(dermoptera,nocturno).

caracteristica(didelphimorphia,theria).
caracteristica(didelphimorphia,metatheria).
caracteristica(didelphimorphia,endemico_america).
caracteristica(didelphimorphia,hocico_alargado).
caracteristica(didelphimorphia,cola_prensil).
caracteristica(didelphimorphia,cola_larga).
caracteristica(didelphimorphia,pelaje).
caracteristica(didelphimorphia,pentadactilo).
caracteristica(didelphimorphia,dientes_cincuenta).
caracteristica(didelphimorphia,poliprotodonto).
caracteristica(didelphimorphia,caninos_desarrollados).
caracteristica(didelphimorphia,carniceras_desarrollados).
caracteristica(didelphimorphia,omnivoro).
caracteristica(didelphimorphia,terrestre).
caracteristica(didelphimorphia,garras).
caracteristica(didelphimorphia,mediano).
caracteristica(didelphimorphia,arboricola).
caracteristica(didelphimorphia,fosorial).
caracteristica(didelphimorphia,macrosmatico).
caracteristica(didelphimorphia,nocturno).
caracteristica(didelphimorphia,plantigrado).

caracteristica(diprotodontia,theria).
caracteristica(diprotodontia,metatheria).
caracteristica(diprotodontia,endemico_australia).
caracteristica(diprotodontia,diprotodonto).
caracteristica(diprotodontia,sindactilos).
caracteristica(diprotodontia,herbivoro).
caracteristica(diprotodontia,terrestre).
caracteristica(diprotodontia,pequeno).
caracteristica(diprotodontia,cola_larga).
caracteristica(diprotodontia,pelaje).
caracteristica(diprotodontia,diastema_marcado).
caracteristica(diprotodontia,labio_leporino).
caracteristica(diprotodontia,incisivos_hipertrofiados).
caracteristica(diprotodontia,garras).
caracteristica(diprotodontia,mediano).
caracteristica(diprotodontia,pentadactilo).
caracteristica(diprotodontia,plantigrado).
caracteristica(diprotodontia,digitigrado).

caracteristica(erinaceomorpha,theria).
caracteristica(erinaceomorpha,eutheria).
caracteristica(erinaceomorpha,insectivoro).
caracteristica(erinaceomorpha,pentadactilo).
caracteristica(erinaceomorpha,pequeno).
caracteristica(erinaceomorpha,hocico_alargado).
caracteristica(erinaceomorpha,puas_o_espinas).
caracteristica(erinaceomorpha,diastema_marcado).
caracteristica(erinaceomorpha,omnivoro).
caracteristica(erinaceomorpha,terrestre).
caracteristica(erinaceomorpha,garras).
caracteristica(erinaceomorpha,plantigrado).
caracteristica(erinaceomorpha,dedos_min_cuatro).
caracteristica(erinaceomorpha,nocturno).
caracteristica(erinaceomorpha,venenoso).
caracteristica(erinaceomorpha,fosorial).
caracteristica(erinaceomorpha,macrosmatico).

caracteristica(hyracoidea,theria).
caracteristica(hyracoidea,eutheria).
caracteristica(hyracoidea,ungulado).
caracteristica(hyracoidea,herbivoro).
caracteristica(hyracoidea,dedos_delanteros_cuatro).
caracteristica(hyracoidea,dedos_traseros_tres).
caracteristica(hyracoidea,sin_caninos).
caracteristica(hyracoidea,plantigrado).
caracteristica(hyracoidea,pequeno).
caracteristica(hyracoidea,pelaje).
caracteristica(hyracoidea,terrestre).
caracteristica(hyracoidea,arboricola).
caracteristica(hyracoidea,incisivos_hipertrofiados).
caracteristica(hyracoidea,diastema_marcado).
caracteristica(hyracoidea,nocturno).

caracteristica(lagomorpha,theria).
caracteristica(lagomorpha,eutheria).
caracteristica(lagomorpha,escroto).
caracteristica(lagomorpha,dedos_min_cuatro).
caracteristica(lagomorpha,incisivos_hipertrofiados).
caracteristica(lagomorpha,diastema_marcado).
caracteristica(lagomorpha,sin_caninos).
caracteristica(lagomorpha,duplidentado).
caracteristica(lagomorpha,pelaje).
caracteristica(lagomorpha,garras).
caracteristica(lagomorpha,incisivos_clavija).
caracteristica(lagomorpha,labio_leporino).
caracteristica(lagomorpha,pentadactilo).
caracteristica(lagomorpha,dedos_impares).
caracteristica(lagomorpha,herbivoro).
caracteristica(lagomorpha,terrestre).
caracteristica(lagomorpha,orejas_largas).
caracteristica(lagomorpha,fosorial).
caracteristica(lagomorpha,nocturno).
caracteristica(lagomorpha,pequeno).
caracteristica(lagomorpha,mediano).

caracteristica(macroscelidea,theria).
caracteristica(macroscelidea,eutheria).
caracteristica(macroscelidea,endemico_africa).
caracteristica(macroscelidea,insectivoro).
caracteristica(macroscelidea,pequeno).
caracteristica(macroscelidea,lengua_protactil).
caracteristica(macroscelidea,pelaje).
caracteristica(macroscelidea,garras).
caracteristica(macroscelidea,cola_larga).
caracteristica(macroscelidea,hocico_proboscide).
caracteristica(macroscelidea,hocico_alargado).
caracteristica(macroscelidea,digitigrado).
caracteristica(macroscelidea,terrestre).
caracteristica(macroscelidea,macrosmatico).
caracteristica(macroscelidea,dedos_min_cuatro).

caracteristica(microbiotheria,theria).
caracteristica(microbiotheria,metatheria).
caracteristica(microbiotheria,endemico_america).
caracteristica(microbiotheria,poliprotodonto).
caracteristica(microbiotheria,herbivoro).
caracteristica(microbiotheria,dientes_cincuenta).
caracteristica(microbiotheria,terrestre).
caracteristica(microbiotheria,pequeno).
caracteristica(microbiotheria,arboricola).
caracteristica(microbiotheria,plantigrado).
caracteristica(microbiotheria,cola_larga).
caracteristica(microbiotheria,cola_prensil).
caracteristica(microbiotheria,pelaje).
caracteristica(microbiotheria,unas_planas).
caracteristica(microbiotheria,pentadactilo).
caracteristica(microbiotheria,dedos_impares).

caracteristica(monotremata,prototheria).
caracteristica(monotremata,sin_dientes).
caracteristica(monotremata,sin_caninos).
caracteristica(monotremata,sin_incisivos).
caracteristica(monotremata,pico).
caracteristica(monotremata,endemico_australia).
caracteristica(monotremata,insectivoro).
caracteristica(monotremata,carnivoro).
caracteristica(monotremata,semiacuatico).
caracteristica(monotremata,terrestre).
caracteristica(monotremata,pelaje).
caracteristica(monotremata,garras).
caracteristica(monotremata,lengua_protactil).
caracteristica(monotremata,hocico_alargado).
caracteristica(monotremata,puas_o_espinas).
caracteristica(monotremata,venenoso).
caracteristica(monotremata,pequeno).
caracteristica(monotremata,dedos_palmeados).
caracteristica(monotremata,dedos_impares).
caracteristica(monotremata,plantigrado).
caracteristica(monotremata,pentadactilo).
caracteristica(monotremata,dedos_min_cuatro).

caracteristica(notoryctemorphia,theria).
caracteristica(notoryctemorphia,metatheria).
caracteristica(notoryctemorphia,endemico_australia).
caracteristica(notoryctemorphia,ojos_diminutos).
caracteristica(notoryctemorphia,ojos_vestigiales).
caracteristica(notoryctemorphia,pentadactilo).
caracteristica(notoryctemorphia,dedos_impares).
caracteristica(notoryctemorphia,insectivoro).
caracteristica(notoryctemorphia,pelaje).
caracteristica(notoryctemorphia,terrestre).
caracteristica(notoryctemorphia,garras).
caracteristica(notoryctemorphia,pequeno).
caracteristica(notoryctemorphia,fosorial).

caracteristica(paucituberculata,theria).
caracteristica(paucituberculata,metatheria).
caracteristica(paucituberculata,endemico_america).
caracteristica(paucituberculata,insectivoro).
caracteristica(paucituberculata,sin_marsupio). %tiene que ser marsupial%
caracteristica(paucituberculata,labio_leporino).
caracteristica(paucituberculata,sindactilos).
caracteristica(paucituberculata,dedos_palmeados).
caracteristica(paucituberculata,poliprotodonto).
caracteristica(paucituberculata,terrestre).
caracteristica(paucituberculata,pequeno).
caracteristica(paucituberculata,pelaje).
caracteristica(paucituberculata,garras).
caracteristica(paucituberculata,dedos_min_cuatro).
caracteristica(paucituberculata,nocturno).

caracteristica(peramelemorphia,theria).
caracteristica(peramelemorphia,metatheria).
caracteristica(peramelemorphia,endemico_australia).
caracteristica(peramelemorphia,hocico_alargado).
caracteristica(peramelemorphia,omnivoro).
caracteristica(peramelemorphia,sindactilos).
caracteristica(peramelemorphia,terrestre).
caracteristica(peramelemorphia,pequeno).
caracteristica(peramelemorphia,pelaje).
caracteristica(peramelemorphia,garras).
caracteristica(peramelemorphia,dedos_min_cuatro).
caracteristica(peramelemorphia,dedos_pares).
caracteristica(peramelemorphia,macrosmatico).
caracteristica(peramelemorphia,nocturno).

caracteristica(perissodactyla,theria).
caracteristica(perissodactyla,eutheria).
caracteristica(perissodactyla,ungulado).
caracteristica(perissodactyla,herbivoro).
caracteristica(perissodactyla,escroto).
caracteristica(perissodactyla,digitigrado).
caracteristica(perissodactyla,pelaje).
caracteristica(perissodactyla,robusto).
caracteristica(perissodactyla,piel_gruesa).
caracteristica(perissodactyla,dedos_impares).
caracteristica(perissodactyla,pezunas).
caracteristica(perissodactyla,terrestre).
caracteristica(perissodactyla,grande).

caracteristica(pholidota,theria).
caracteristica(pholidota,eutheria).
caracteristica(pholidota,escroto).
caracteristica(pholidota,dedos_min_cuatro).
caracteristica(pholidota,escamas).
caracteristica(pholidota,sin_dientes).
caracteristica(pholidota,sin_caninos).
caracteristica(pholidota,sin_incisivos).
caracteristica(pholidota,cola_larga).
caracteristica(pholidota,cola_prensil).
caracteristica(pholidota,hocico_alargado).
caracteristica(pholidota,lengua_protactil).
caracteristica(pholidota,piel_gruesa).
caracteristica(pholidota,garras).
caracteristica(pholidota,plantigrado).
caracteristica(pholidota,insectivoro).
caracteristica(pholidota,terrestre).
caracteristica(pholidota,pequeno).
caracteristica(pholidota,mediano).
caracteristica(pholidota,arboricola).
caracteristica(pholidota,nocturno).
caracteristica(pholidota,fosorial).
caracteristica(pholidota,macrosmatico).

caracteristica(pilosa,theria).
caracteristica(pilosa,eutheria).
caracteristica(pilosa,articulaciones_xenartrales).
caracteristica(pilosa,sin_dientes).
caracteristica(pilosa,sin_caninos).
caracteristica(pilosa,sin_incisivos).
caracteristica(pilosa,dientes_no_desarrollados).
caracteristica(pilosa,pelaje).
caracteristica(pilosa,terrestre).
caracteristica(pilosa,herbivoro).
caracteristica(pilosa,insectivoro).
caracteristica(pilosa,garras).
caracteristica(pilosa,hocico_alargado).
caracteristica(pilosa,lengua_protactil).
caracteristica(pilosa,cola_larga).
caracteristica(pilosa,cola_prensil).
caracteristica(pilosa,mediano).
caracteristica(pilosa,arboricola).

caracteristica(primates,theria).
caracteristica(primates,eutheria).
caracteristica(primates,escroto).
caracteristica(primates,dedos_min_cuatro).
caracteristica(primates,pentadactilo).
caracteristica(primates,plantigrado).
caracteristica(primates,vision_desarrollado).
caracteristica(primates,huellas_digitales).
caracteristica(primates,unas_planas).
caracteristica(primates,omnivoro).
caracteristica(primates,terrestre).
caracteristica(primates,pequeno).
caracteristica(primates,mediano).
caracteristica(primates,grande).
caracteristica(primates,bipedo).
caracteristica(primates,arboricola).
caracteristica(primates,dedos_impares).
caracteristica(primates,cola_larga).
caracteristica(primates,cola_prensil).
caracteristica(primates,pelaje).

caracteristica(proboscidea,theria).
caracteristica(proboscidea,eutheria).
caracteristica(proboscidea,ungulado).
caracteristica(proboscidea,herbivoro).
caracteristica(proboscidea,pentadactilo).
caracteristica(proboscidea,robusto).
caracteristica(proboscidea,piel_gruesa).
caracteristica(proboscidea,hocico_proboscide).
caracteristica(proboscidea,terrestre).
caracteristica(proboscidea,incisivos_desarrollados).
caracteristica(proboscidea,sin_caninos).
caracteristica(proboscidea,hocico_alargado).
caracteristica(proboscidea,incisivos_hipertrofiados).
caracteristica(proboscidea,dedos_impares).
caracteristica(proboscidea,dedos_min_cuatro).
caracteristica(proboscidea,orejas_largas).
caracteristica(proboscidea,muy_grande).
caracteristica(proboscidea,unas_planas).

caracteristica(rodentia,theria).
caracteristica(rodentia,escroto).
caracteristica(rodentia,dedos_min_cuatro).
caracteristica(rodentia,incisivos_hipertrofiados).
caracteristica(rodentia,diastema_marcado).
caracteristica(rodentia,sin_caninos).
caracteristica(rodentia,dedos_delanteros_cinco).
caracteristica(rodentia,dedos_traseros_cuatro).
caracteristica(rodentia,omnivoro).
caracteristica(rodentia,incisivos_superiores_dos).
caracteristica(rodentia,incisivos_inferiores_dos).
caracteristica(rodentia,terrestre).
caracteristica(rodentia,pequeno).
caracteristica(rodentia,mediano).
caracteristica(rodentia,nocturno).
caracteristica(rodentia,arboricola).
caracteristica(rodentia,pelaje).
caracteristica(rodentia,garras).
caracteristica(rodentia,unas_planas).
caracteristica(rodentia,cola_larga).
caracteristica(rodentia,cola_prensil).

caracteristica(scandentia,theria).
caracteristica(scandentia,eutheria).
caracteristica(scandentia,escroto).
caracteristica(scandentia,dedos_min_cuatro).
caracteristica(scandentia,pentadactilo).
caracteristica(scandentia,plantigrado).
caracteristica(scandentia,arboricola).
caracteristica(scandentia,nocturno).
caracteristica(scandentia,endemico_asia).
caracteristica(scandentia,omnivoro).
caracteristica(scandentia,cola_larga).
caracteristica(scandentia,terrestre).
caracteristica(scandentia,hocico_alargado).
caracteristica(scandentia,pequeno).
caracteristica(scandentia,garras).
caracteristica(scandentia,pelaje).
caracteristica(scandentia,dedos_impares).

caracteristica(sirenia,theria).
caracteristica(sirenia,eutheria).
caracteristica(sirenia,ungulado).
caracteristica(sirenia,herbivoro).
caracteristica(sirenia,pentadactilo).
caracteristica(sirenia,robusto).
caracteristica(sirenia,piel_gruesa).
caracteristica(sirenia,hocico_proboscide).
caracteristica(sirenia,aletas).
caracteristica(sirenia,acuatico).
caracteristica(sirenia,grande).
caracteristica(sirenia,muy_grande).
caracteristica(sirenia,unas_planas).
caracteristica(sirenia,dedos_impares).
caracteristica(sirenia,dedos_min_cuatro).

caracteristica(soricomorpha,theria).
caracteristica(soricomorpha,eutheria).
caracteristica(soricomorpha,insectivoro).
caracteristica(soricomorpha,pentadactilo).
caracteristica(soricomorpha,pequeno).
caracteristica(soricomorpha,hocico_alargado).
caracteristica(soricomorpha,ojos_diminutos).
caracteristica(soricomorpha,ojos_vestigiales).
caracteristica(soricomorpha,caninos_desarrollados).
caracteristica(soricomorpha,carniceras_desarrollados).
caracteristica(soricomorpha,terrestre).
caracteristica(soricomorpha,plantigrado).
caracteristica(soricomorpha,nocturno).
caracteristica(soricomorpha,venenoso).
caracteristica(soricomorpha,fosorial).
caracteristica(soricomorpha,macrosmatico).
caracteristica(soricomorpha,garras).
caracteristica(soricomorpha,pelaje).
caracteristica(soricomorpha,dedos_impares).

caracteristica(tubulidentata,theria).
caracteristica(tubulidentata,eutheria).
caracteristica(tubulidentata,endemico_africa).
caracteristica(tubulidentata,insectivoro).
caracteristica(tubulidentata,dientes_tubulados).
caracteristica(tubulidentata,sin_caninos).
caracteristica(tubulidentata,sin_incisivos).
caracteristica(tubulidentata,hocico_proboscide).
caracteristica(tubulidentata,lengua_protactil).
caracteristica(tubulidentata,ungulado).
caracteristica(tubulidentata,terrestre).
caracteristica(tubulidentata,hocico_alargado).
caracteristica(tubulidentata,garras).
caracteristica(tubulidentata,dedos_delanteros_cuatro).
caracteristica(tubulidentata,dedos_traseros_cinco).
caracteristica(tubulidentata,mediano).
caracteristica(tubulidentata,fosorial).
caracteristica(tubulidentata,nocturno).
caracteristica(tubulidentata,digitigrado).
caracteristica(tubulidentata,piel_gruesa).



caracteristica(cetartiodactyla,theria).
caracteristica(cetartiodactyla,eutheria).
caracteristica(cetartiodactyla,ungulado).
caracteristica(cetartiodactyla,dedos_pares).
caracteristica(cetartiodactyla,carnivoro).
caracteristica(cetartiodactyla,herbivoro).
caracteristica(cetartiodactyla,digitigrado).
caracteristica(cetartiodactyla,terrestre).
caracteristica(cetartiodactyla,acuatico).
caracteristica(cetartiodactyla,pequeno).
caracteristica(cetartiodactyla,mediano).
caracteristica(cetartiodactyla,grande).
caracteristica(cetartiodactyla,muy_grande).

caracteristica(eulipotyphla,theria).
caracteristica(eulipotyphla,eutheria).
caracteristica(eulipotyphla,insectivoro).
caracteristica(eulipotyphla,pentadactilo).
caracteristica(eulipotyphla,pequeno).
caracteristica(eulipotyphla,hocico_alargado).
caracteristica(eulipotyphla,terrestre).
caracteristica(eulipotyphla,plantigrado).
caracteristica(eulipotyphla,nocturno).
caracteristica(eulipotyphla,venenoso).
caracteristica(eulipotyphla,fosorial).
caracteristica(eulipotyphla,macrosmatico).
